POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpMTIiLCJpZCI6IjVlYmJiYjY2MjNkY2U1M2Q2ZmM0ZmIyOCIsImlhdCI6MTU4OTM2Mjg1OX0.OuaMBFUOjdS7M4mvXszAqZJRShtHBiOzyacWjkqu3_U

{
  "title": "testi3",
  "author": "lol lol",
  "url": "x.x.com",
  "likes": 5
}
